In [13]:
from numpy import *
a = arange(1,16)
print(a.reshape(3,5).T)
def f(x,y):
    return 5*y+x + 1
b = fromfunction(f,(5,3),dtype=int)

print(b)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]
[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [8]:
import numpy as np
a = np.arange(25).reshape(5, 5)
b = np.array([1., 5, 10, 15, 20])
a,b


(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]), array([  1.,   5.,  10.,  15.,  20.]))