In [54]:
import numpy as np
from random import random
P = np.random.rand(5,5)
row_sums = P.sum(axis=1)
P = P / row_sums[:, np.newaxis]
print(P)
print(np.sum(P,axis=1))
    
    

[[ 0.19181913  0.3375524   0.13181313  0.15300122  0.18581413]
 [ 0.76679546  0.12735357  0.06109662  0.02471261  0.02004174]
 [ 0.373423    0.24146287  0.2417102   0.0689375   0.07446642]
 [ 0.00603921  0.2792419   0.24517447  0.30445053  0.16509388]
 [ 0.0310008   0.17215383  0.32607752  0.21885447  0.25191337]]
[ 1.  1.  1.  1.  1.]


In [55]:
pc = np.random.rand(5,1)
sp = pc.sum(axis=0)
pc = pc / sp
print(pc)

[[ 0.33286091]
 [ 0.1872566 ]
 [ 0.01548351]
 [ 0.09524914]
 [ 0.36914984]]


In [56]:
p0 = pc
p1 = np.dot(P.T,p0)
p2 = np.dot(P.T,p1)
p3 = np.dot(P.T,p2)
print(p0,p1,p2,p3)

    
    

[[ 0.33286091]
 [ 0.1872566 ]
 [ 0.01548351]
 [ 0.09524914]
 [ 0.36914984]] [[ 0.22523767]
 [ 0.2300926 ]
 [ 0.20278283]
 [ 0.16641186]
 [ 0.17547504]] [[ 0.30180749]
 [ 0.23097502]
 [ 0.19078025]
 [ 0.14319485]
 [ 0.1332424 ]] [[ 0.31124018]
 [ 0.24028187]
 [ 0.17856259]
 [ 0.13779327]
 [ 0.13212209]]


In [57]:
for i in range(50):
    pcc = np.array(pc)
    pc = np.dot(P.T, pcc)
    #print(pc)

In [74]:

def sumabs(x):
    return sum(abs(x))
eigvalue, eigenvectors = np.linalg.eig(P.T)

j_stationary = np.argmin(abs(eigvalue - 1.0))
p_stationary = eigenvectors [:,j_stationary].real
p_stationary /= p_stationary.sum()
print(p_stationary)

#row_sums = eigv.sum(axis=1)
#P = eigv  / row_sums[:, np.newaxis]
row_sums = np.apply_along_axis(sumabs,1,eigenvectors )
eigenvectors = eigenvectors / row_sums[:, np.newaxis]
eigenvectors 

[ 0.31511689  0.24031682  0.17531705  0.13688091  0.13236832]


array([[ 0.11234921+0.j        ,  0.28927162+0.j        ,
         0.23671003+0.j        ,  0.23671003-0.j        ,  0.12495912+0.j        ],
       [ 0.18628770+0.j        , -0.40451187+0.j        ,
         0.15490123-0.03483541j,  0.15490123+0.03483541j, -0.09166053+0.j        ],
       [ 0.11207581+0.j        ,  0.03362725+0.j        ,
        -0.30734283+0.22436416j, -0.30734283-0.22436416j,  0.09324795+0.j        ],
       [ 0.08193252+0.j        , -0.06426327+0.j        ,
        -0.18125566-0.03482187j, -0.18125566+0.03482187j, -0.48466372+0.j        ],
       [ 0.10030067+0.j        , -0.17788413+0.j        ,
        -0.06074641-0.18780755j, -0.06074641+0.18780755j,  0.32704031+0.j        ]])