In [1]:
from numpy  import *
a = arange(15).reshape(3, 5)

In [2]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
print("a.ndim = {}".format(a.ndim))
print("a.shape = {}".format(a.shape))
print("a.size = {}".format(a.shape))
print("a.itemsize = {}".format(a.shape))
print("a.data = {}".format(a.shape))



a.ndim = 2
a.shape = (3, 5)
a.size = (3, 5)
a.itemsize = (3, 5)
a.data = (3, 5)


In [5]:
a = array([1,2,3,4])
b = array( [ (1.5,2,3), (4,5,6) ] )
c = array( [ [1,2], [3,4] ], dtype=complex )
print("====  a  ====",a,sep='\n')
print("====  b  ====",b,sep='\n')
print("====  c  ====",c,sep='\n')


====  a  ====
[1 2 3 4]
====  b  ====
[[ 1.5  2.   3. ]
 [ 4.   5.   6. ]]
====  c  ====
[[ 1.+0.j  2.+0.j]
 [ 3.+0.j  4.+0.j]]


In [6]:
print("zeros( (3,4) )", zeros( (3,4) ), sep='\n')
print("ones( (2, 3, 4), dtype=int16   )", ones( (2, 3, 4), dtype=int16   ), sep='\n')


zeros( (3,4) )
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
ones( (2, 3, 4), dtype=int16   )
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [7]:
print("arange( 10, 30, 5 )", arange( 10, 30, 5 ), sep='\n')
print("arange( 0, 2, 0.3 )", arange( 0, 2, 0.3 ), sep='\n')

arange( 10, 30, 5 )
[10 15 20 25]
arange( 0, 2, 0.3 )
[ 0.   0.3  0.6  0.9  1.2  1.5  1.8]


In [8]:
print( "linspace( 0, 2, 9 )",  linspace( 0, 2, 9 ), sep='\n')
print( "linspace( 0, 2*pi, 100 )",  linspace( 0, 2*pi, 100), sep='\n')

linspace( 0, 2, 9 )
[ 0.    0.25  0.5   0.75  1.    1.25  1.5   1.75  2.  ]
linspace( 0, 2*pi, 100 )
[ 0.          0.06346652  0.12693304  0.19039955  0.25386607  0.31733259
  0.38079911  0.44426563  0.50773215  0.57119866  0.63466518  0.6981317
  0.76159822  0.82506474  0.88853126  0.95199777  1.01546429  1.07893081
  1.14239733  1.20586385  1.26933037  1.33279688  1.3962634   1.45972992
  1.52319644  1.58666296  1.65012947  1.71359599  1.77706251  1.84052903
  1.90399555  1.96746207  2.03092858  2.0943951   2.15786162  2.22132814
  2.28479466  2.34826118  2.41172769  2.47519421  2.53866073  2.60212725
  2.66559377  2.72906028  2.7925268   2.85599332  2.91945984  2.98292636
  3.04639288  3.10985939  3.17332591  3.23679243  3.30025895  3.36372547
  3.42719199  3.4906585   3.55412502  3.61759154  3.68105806  3.74452458
  3.8079911   3.87145761  3.93492413  3.99839065  4.06185717  4.12532369
  4.1887902   4.25225672  4.31572324  4.37918976  4.44265628  4.5061228
  4.56958931  4.63305583 

In [2]:
 from numpy import *
 print("arange(6)",arange(6),sep='\n')
 print("arange(12).reshape(4,3)",arange(12).reshape(4,3),sep='\n')
 print("arange(24).reshape(2,3,4)",arange(24).reshape(2,3,4),sep='\n')

arange(6)
[0 1 2 3 4 5]
arange(12).reshape(4,3)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
arange(24).reshape(2,3,4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [3]:
print(arange(10000))

[   0    1    2 ..., 9997 9998 9999]


In [6]:
 print(arange(10000).reshape(100,100))

[[   0    1    2 ...,   97   98   99]
 [ 100  101  102 ...,  197  198  199]
 [ 200  201  202 ...,  297  298  299]
 ..., 
 [9700 9701 9702 ..., 9797 9798 9799]
 [9800 9801 9802 ..., 9897 9898 9899]
 [9900 9901 9902 ..., 9997 9998 9999]]


In [ ]:
set_printoptions(threshold='nan')
print(arange(10000))

TypeError: '>' not supported between instances of 'int' and 'str'

In [10]:
set_printoptions(threshold=1000)
print(arange(10000))

[   0    1    2 ..., 9997 9998 9999]


In [11]:
a = array( [20,30,40,50] )
b = arange( 4 )
print('b',b,sep='\n')
c = a-b
print('c',c,sep='\n')
print('b**2',b**2,sep='\n')
print('10*sin(a)',10*sin(a),sep='\n')
print('a<35',a<35,sep='\n')


b
[0 1 2 3]
c
[20 29 38 47]
b**2
[0 1 4 9]
10*sin(a)
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]
a<35
[ True  True False False]


In [12]:
A = array( [[1,1],
            [0,1]] )
B = array( [[2,0],
            [3,4]] )
print("A*B",A*B,sep='\n')                         # elementwise product
print("dot(A,B)",dot(A,B),sep='\n')


A*B
[[2 0]
 [0 4]]
dot(A,B)
[[5 4]
 [3 4]]


In [18]:
a = ones((2,3))
b = random.random((2,3))
a *= 3
print("a",a,sep='\n')
b += a
print("b",b,sep='\n')
a += b                                  # b is converted to integer type
print("a",a,sep='\n')



a
[[ 3.  3.  3.]
 [ 3.  3.  3.]]
b
[[ 3.4079429   3.15008325  3.004162  ]
 [ 3.1516612   3.25090474  3.91949062]]
a
[[ 6.4079429   6.15008325  6.004162  ]
 [ 6.1516612   6.25090474  6.91949062]]


In [19]:
a = ones(3, dtype=int32)
b = linspace(0,pi,3)
b.dtype.name
c = a+b
print("c",c,sep='\n')
c.dtype.name
d = exp(c*1j)
print("d",d,sep='\n')
d.dtype.name

c
[ 1.          2.57079633  4.14159265]
d
[ 0.54030231+0.84147098j -0.84147098+0.54030231j -0.54030231-0.84147098j]


'complex128'

In [20]:
a = random.random((2,3))
print("a",a,sep='\n')
print("a.sum()",a.sum(),sep='\n')
print("a.min()",a.max(),sep='\n')
print("a.min()",a.max(),sep='\n')


a
[[ 0.54453131  0.6498652   0.1616362 ]
 [ 0.10223657  0.54596983  0.16876136]]
a.sum()
2.1730004737
a.min()
0.649865198142
a.min()
0.649865198142


In [21]:
b = arange(12).reshape(3,4)
print("b",b,sep='\n')
print("b.sum(axis=0)",b.sum(axis=0),sep='\n')
print("b.min(axis=1)",b.min(axis=1),sep='\n')
print("b.cumsum(axis=1)",b.cumsum(axis=1),sep='\n')
                            # sum of each column
                            # min of each row
                         # cumulative sum along each row


b
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
b.sum(axis=0)
[12 15 18 21]
b.min(axis=1)
[0 4 8]
b.cumsum(axis=1)
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


In [23]:
B = arange(3)
print("B",B,sep='\n')
print("exp(B)",exp(B),sep='\n')
print("sqrt(B)", sqrt(B),sep='\n')

C = array([2., -1., 4.])
print("C",C,sep='\n')

print("add(B, C)", add(B, C),sep='\n')



B
[0 1 2]
exp(B)
[ 1.          2.71828183  7.3890561 ]
sqrt(B)
[ 0.          1.          1.41421356]
C
[ 2. -1.  4.]
add(B, C)
[ 2.  0.  6.]


In [26]:
a = arange(10)**3
print(a)
print(a[2])

print(a[2:5])
print(a[:6:2])
print(a[ : :-1])                                 # reversed a
for i in a:
    print(i**(1/3.),)


[  0   1   8  27  64 125 216 343 512 729]
8
[ 8 27 64]
[ 0  8 64]
[729 512 343 216 125  64  27   8   1   0]
0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0


In [34]:
def f(x,y):
    return 10*x+y

b = fromfunction(f,(5,4),dtype=int)
print(b)
array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])
print(b[2,3])

print(b[0:5, 1])                       # each row in the second column of b
print(b[ : ,1])                        # equivalent to the previous example
print(b[1:3, : ])                      # each column in the second and third row of b
print(b[-1])
for row in b:
    print(row)
for element in b.flat:
    print(element)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
23
[ 1 11 21 31 41]
[ 1 11 21 31 41]
[[10 11 12 13]
 [20 21 22 23]]
[40 41 42 43]
[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [28]:
b[-1]                                  # the last row. Equivalent to b[-1,:]
array([40, 41, 42, 43])

array([40, 41, 42, 43])

In [31]:
c = array( [ [[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
    [ 10, 12, 13]],

    [[100,101,102],
    [110,112,113]] ] )
print(c.shape)
print(c[1,...])                                   # same as c[1,:,:] or c[1]
print(c[...,2])                                   # same as c[:,:,2]


(2, 2, 3)
[[100 101 102]
 [110 112 113]]
[[  2  13]
 [102 113]]


In [7]:
from numpy  import floor
from  numpy import random
a = floor(10*random.random((3,4)))
a.transpose()

array([[ 7.,  2.,  2.],
       [ 1.,  1.,  5.],
       [ 7.,  1.,  9.],
       [ 1.,  4.,  0.]])

In [9]:
a.resize((2,6))

In [10]:
a

array([[ 7.,  1.,  7.,  1.,  2.,  1.],
       [ 1.,  4.,  2.,  5.,  9.,  0.]])

In [12]:
from numpy import *
a = floor(10*random.random((2,2)))
b = floor(10*random.random((2,2)))
print(vstack((a,b)))
print(hstack((a,b)))

[[ 9.  5.]
 [ 7.  0.]
 [ 8.  1.]
 [ 8.  5.]]
[[ 9.  5.  8.  1.]
 [ 7.  0.  8.  5.]]


In [14]:
print(column_stack((a,b)))   # With 2D arrays
a=array([4.,2.])
b=array([2.,8.])
print(a[:,newaxis])  # This allows to have a 2D columns vector
print(column_stack((a[:,newaxis],b[:,newaxis])))

print(vstack((a[:,newaxis],b[:,newaxis])))


[[ 4.  2.]
 [ 2.  8.]]
[[ 4.]
 [ 2.]]
[[ 4.  2.]
 [ 2.  8.]]
[[ 4.]
 [ 2.]
 [ 2.]
 [ 8.]]


In [16]:
print(r_[1:4,0,4])

[1 2 3 0 4]


In [17]:
a = floor(10*random.random((2,12)))
print(a)
print(hsplit(a,3))

print(hsplit(a,(3,4)))


[[ 5.  2.  7.  0.  5.  6.  4.  2.  9.  7.  7.  8.]
 [ 5.  8.  5.  7.  4.  2.  3.  3.  0.  2.  2.  6.]]
[array([[ 5.,  2.,  7.,  0.],
       [ 5.,  8.,  5.,  7.]]), array([[ 5.,  6.,  4.,  2.],
       [ 4.,  2.,  3.,  3.]]), array([[ 9.,  7.,  7.,  8.],
       [ 0.,  2.,  2.,  6.]])]
[array([[ 5.,  2.,  7.],
       [ 5.,  8.,  5.]]), array([[ 0.],
       [ 7.]]), array([[ 5.,  6.,  4.,  2.,  9.,  7.,  7.,  8.],
       [ 4.,  2.,  3.,  3.,  0.,  2.,  2.,  6.]])]


In [18]:
c = a.view()
print(c is a)

print(c.base is a)                        # c is a view of the data owned by a

print(c.flags.owndata)
print(c.shape, a.shape, c[0,4])                      # a's shape doesn't change
print(a)

False
True
False
(2, 12) (2, 12) 5.0
[[ 5.  2.  7.  0.  5.  6.  4.  2.  9.  7.  7.  8.]
 [ 5.  8.  5.  7.  4.  2.  3.  3.  0.  2.  2.  6.]]


In [20]:
s = a[ : , 1:3]     # spaces added for clarity; could also be written "s = a[:,1:3]"
s[:] = 10           # s[:] is a view of s. Note the difference between s=10 and s[:]=10
print(a)

[[  5.  10.  10.   0.   5.   6.   4.   2.   9.   7.   7.   8.]
 [  5.  10.  10.   7.   4.   2.   3.   3.   0.   2.   2.   6.]]


In [22]:
d = a.copy()                          # a new array object with new data is created
print(d is a)

print(d.base is a)                           # d doesn't share anything with a

d[0,0] = 9999
print(a)


False
False
[[  5.  10.  10.   0.   5.   6.   4.   2.   9.   7.   7.   8.]
 [  5.  10.  10.   7.   4.   2.   3.   3.   0.   2.   2.   6.]]


In [24]:
a = arange(12)**2                          # the first 12 square numbers
i = array( [ 1,1,3,8,5 ] )                 # an array of indices
print(a[i])                                       # the elements of a at the positions i
j = array( [ [ 3, 4], [ 9, 7 ] ] )         # a bidimensional array of indices
print(a[j])                                       # the same shape as j


[ 1  1  9 64 25]
[[ 9 16]
 [81 49]]


In [26]:
palette = array( [ [0,0,0],                # black
                [255,0,0],              # red
                [0,255,0],              # green
                [0,0,255],              # blue
                [255,255,255] ] )       # white
image = array( [ [ 0, 1, 2, 0 ],           # each value corresponds to a color in the palette
                [ 0, 3, 4, 0 ]  ] )
print(palette[image])                            # the (2,4,3) color image


[[[  0   0   0]
  [255   0   0]
  [  0 255   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0 255]
  [255 255 255]
  [  0   0   0]]]
