In [1]:
from numpy import *
a = array([1,2,3])
print(all(a > 0)) # equivalent to (a > 0).all()


True


In [2]:
a = array([1,2,3])
print((a >= 1).any()) 


True


In [4]:
from numpy import *
a = array([10,20,30,40])
print(append(a,50))
print(append(a,[50,60]))

a = array([[10,20,30],[40,50,60],[70,80,90]])

print(append(a,[[15,15,15]],axis=0))

print(append(a,[[15],[15],[15]],axis=1))


[10 20 30 40 50]
[10 20 30 40 50 60]
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 15 15]]
[[10 20 30 15]
 [40 50 60 15]
 [70 80 90 15]]


In [5]:
from numpy import *
def myfunc(a): # function works on a 1d arrays, takes the average of the 1st an last element
    return (a[0]+a[-1])/2

b = array([[1,2,3],[4,5,6],[7,8,9]])
print(apply_along_axis(myfunc,0,b)) # apply myfunc to each column (axis=0) of b

print(apply_along_axis(myfunc,1,b)) # apply myfunc to each row (axis=1) of b


[ 4.  5.  6.]
[ 2.  5.  8.]
